version: 2.1

defaults: &defaults
  docker:
    - image: quay.io/stackrox-io/apollo-ci:stackrox-build-0.3.51
  working_directory: /home/circleci/go/src/github.com/stackrox/k8s-istio-cve-pusher


setupGoogleAppCreds: &setupGoogleAppCreds
  run:
    name: Setup GCloud Service Account
    command: |
      touch /tmp/gcp.json
      chmod 0600 /tmp/gcp.json
      echo "$GOOGLE_PUSHER_SA_CREDENTIALS" >/tmp/gcp.json
      cci-export GOOGLE_APPLICATION_CREDENTIALS /tmp/gcp.json

jobs:
  build:
    <<: *defaults
    environment:
      - GOOGLE_CLOUD_BUCKET: ns-test
    steps:
      - checkout
      - *setupGoogleAppCreds
      - run:
          name: Build
          command: make build
      - run:
          name: Run tests
          command: make test
      - run:
          name: Run integration test
          command: ./image/cve-uploader -gcs-bucket-name "$GOOGLE_CLOUD_BUCKET" -gcs-bucket-prefix cve

workflows:
  build:
    jobs:
      - build:
          context: docker-io-pull
