version: 2.1

defaults: &defaults
  docker:
    - image: docker.io/stackrox/apollo-ci:0.2.3
      auth:
        username: $DOCKER_IO_PULL_USERNAME
        password: $DOCKER_IO_PULL_PASSWORD
  working_directory: /home/circleci/go/src/github.com/stackrox/k8s-istio-cve-pusher


setupGoogleAppCreds: &setupGoogleAppCreds
  run:
    name: Setup GCloud Service Account
    command: |
      touch /tmp/gcp.json
      chmod 0600 /tmp/gcp.json
      echo "$GOOGLE_PUSHER_SA_CREDENTIALS" >/tmp/gcp.json
      cci-export GOOGLE_APPLICATION_CREDENTIALS /tmp/gcp.json

jobs:
  push:
    <<: *defaults
    environment:
      - LOCAL_FILE_PATH: /home
      - GOOGLE_CLOUD_BUCKET: ns-test
    # working_directory: /home/circleci/go/src/github.com/stackrox/k8s-istio-cve-pusher/main
    steps:
      - checkout
      - *setupGoogleAppCreds
      - run:
          name: Install dependencies
          command: go get ./...
      - run:
          name: Build
          command: pwd && ls && go build ./main/main.go
      - run:
          name: Run tests
          command: go test ./main -v
      - run:
          name: Run job
          command: pwd && ls ./main

workflows:
  version: 2
  build_all:
    jobs:
      - push:
          context: docker-io-pull
          filters:
            branches:
              only:
                - master
                - ROX-3428

#workflows:
#  cron:
#    jobs:
#      - push:
#          context: docker-io-pull
#          filters:
#            branches:
#              only:
#                - master
#                - ROX-3428
#    triggers:
#      - schedule:
#          cron: "0 * * * *"
#          filters:
#            branches:
#              only:
#                - master
#                - ROX-3428