name: Upload

on:
  schedule:
    # Run hourly on the 15-minute mark.
    - cron: '15 * * * *'

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    container:
      image: quay.io/rhacs-eng/qa:cve-uploader-latest
      credentials:
        username: ${{ secrets.QUAY_RHACS_ENG_RW_USERNAME }}
        password: ${{ secrets.QUAY_RHACS_ENG_RW_PASSWORD }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /credentials.json

    steps:
      - name: Upload CVE data
        run: |
          install -m 600 /dev/null /credentials.json
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >/credentials.json
          /usr/bin/cve-uploader -gcs-bucket-name=definitions.stackrox.io -gcs-bucket-prefix=cve2
